site_name: Eatelicious Documentation
repo_name: Eatelicious
repo_url: https://github.com/Saroj-Maharjan/Eatelicious

theme:
  name: material
  icon:
    logo: octicons/rocket-24
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: white
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference

  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - content.action.view
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:saroj.maharjan1993@gmail.com
    - icon: fontawesome/brands/github
      link: https://github.com/Saroj-Maharjan
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ji-saroj-maharjan
    - icon: fontawesome/brands/stack-overflow
      link: https://stackoverflow.com/users/12737399/atick-faisal

plugins:
  - search
  - tags

copyright: Copyright &copy; 2023 Saroj Maharjan